language: elixir
elixir:
  - 1.10.2
otp_release:
  - 22.3
script:
  - mix format --check-formatted
  - mix test
  - mix compile --warnings-as-errors
  - mix credo --all --strict
  - mix dialyzer
cache:
  directories:
  - _build/dev
